CREATE DATABASE book_Store;
USE book_Store;
-- Table named books has already been created and data has been filled

-- CONCAT
SELECT CONCAT(Author_fname,'!!!') FROM books; -- Concatenate authore name with !!!
SELECT CONCAT(Author_fname, NULL) AS Author FROM books; -- Concatenate with NULL = NULL
-- Use aliases for better reading
SELECT CONCAT(author_fname,' ',author_lname) AS "Author\"s Name" FROM books;
-- CONCAT_WS
SELECT CONCAT_WS('---',author_fname,author_lname) FROM books; -- 'Concat with' operator.
-- CONCAT END

-- SUBSTRING
-- SELECT SUBSTIRNG(TEXT, STARING INDEX, LENGTH) INDEX START FROM 1 NOT 0.
SELECT SUBSTRING('HELLO WORLD',1,4);
SELECT SUBSTRING('HELLO WORLD',5); -- IF WE DON'T PROVIDE TH LENGHT, IT WILL GO TILL THE END
SELECT SUBSTRING('HELLO WORLD',-6,4); -- START THE INDEXING FROM THE END OF STRING AND THEN GO FORWARD

-- FIRST CHARACTER OF AUTHOR LAST NAME
SELECT SUBSTRING(author_lname,1,1) FROM books;

-- SUBSTR() IS SYNONYMS FOR SUBSTRING()
SELECT SUBSTR('HELLO WORLD',2,5);

-- SUBTRING WITH FROM AND FOR
SELECT SUBSTR('HELLO WORLD' FROM 3);
SELECT SUBSTR('HELLO WORLD' FROM 3 FOR 5);
  
-- SUBSTRING End

-- COMBINING SUBSTRING AND CONCAT
SELECT CONCAT(SUBSTR(title,1,10),'...') AS Short_Title FROM books;
-- COMBINING SUBSTRING AND CONCAT END

-- REPLACE
SELECT REPLACE('HELLO WORLD','HELL','45#$$#');
SELECT REPLACE('HELLO WORLD !',' ', ' AND ');
SELECT REPLACE('HELLO WORLD HELLO','HELLO', ' AND '); -- REPLACE ALL THE CHARACTER THAT MATCHES THE ARGUMENT
SELECT -- IT IS CASE SENSITIVE, WON'T GIVE ERROR BUT WON'T WORK EITHER
  REPLACE('cheese bread coffee milk', 'CHEESE', ' and ');
-- FROM BOOKS
SELECT
	REPLACE(title,' ','-') FROM books;
-- USING REPLACE WITH UPDATE    
UPDATE books SET title=REPLACE(title,' ','4') ; -- DISABLE SAFE MODE FIRST
-- REPLACE END

-- REVERSE
SELECT REVERSE('HELLO');
SELECT REVERSE(AUTHOR_FNAME) FROM books;
SELECT CONCAT(author_fname, REVERSE(author_fname)) FROM books;
-- REVERSE END

-- CHAR_LENGHT AND LENGHT
SELECT CHAR_LENGTH('DOLPHIN'); -- WILL COUNT LENGHT BY NUMBER OF CHARACTER
SELECT LENGTH('HELLO'); -- WILL COUNT LENGHT BY NUMBER OF BYTES
SELECT CHAR_LENGTH(title) AS length, title FROM books;
SELECT CONCAT(
	author_lname, ' is ', CHAR_LENGTH(author_lname), ' characters long'
    ) AS 'Last name character info'
	FROM books;
-- CHAR_LENGHT AND LENGHT END 

-- UPPER AND LOWER (UCASE AND LCASE)
SELECT LOWER('Hello World');
 
SELECT UPPER(title) FROM books;
SELECT LCASE(title) FROM books; 
-- UPPER AND LOWER (UCASE AND LCASE) END

-- INSERT(OLD_STRING, POSTION, NUMBER OF CHARACTER TO BE REPLACED, STRING_TO_INSERT)
SELECT INSERT('HELLO WORLD',6,0,'NEW');
SELECT INSERT('HELLO WORLD',6,4,'NEW');
SELECT INSERT('HELLO WORLD',6,40,'NEW'); -- IF NO. OF CHARACTER TO BE REPLACED > ACTUAL CHARACTER
-- INSER END

-- LEFT RIGHT
SELECT LEFT('omghahalol!', 3);
SELECT RIGHT('omghahalol!', 4);
-- LEFT RIGHT END

-- REPEAT
SELECT REPEAT('ha', 4);
-- REPEAT END
 
 -- TRIM
SELECT TRIM('  pickle  ');
SELECT TRIM(LEADING '.' FROM '....HELLO....');
SELECT TRIM(TRAILING '.' FROM '....HELLO....');
SELECT TRIM(BOTH '.' FROM '....HELLO....');
SELECT * FROM books;
SET SQL_SAFE_UPDATES = 0;